name: SLSA Provenance Generation and Verification

on:
  workflow_call:
    inputs:
      artifact_path:
        description: "The path to the generated artifacts."
        required: false
        type: string

jobs:
  generate-and-verify-slsa:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 1: Set default artifact path if input is null
      - name: Set artifact path
        id: set-artifact-path
        run: |
          DEFAULT_PATH="./default-artifacts"
          if [ -z "${{ inputs.artifact_path }}" ]; then
            echo "artifact_path=$DEFAULT_PATH" >> $GITHUB_ENV
          else
            echo "artifact_path=${{ inputs.artifact_path }}" >> $GITHUB_ENV
          fi
          mkdir -p ${{ env.artifact_path }}

      # Step 2: Build and Generate Provenance for Maven 
      - name: Set up Java environment
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Build Maven project
        run: mvn clean package -DskipTests

      - name: Generate SLSA Provenance for Maven
        uses: slsa-framework/slsa-github-generator/.github/workflows/builder_maven_slsa3.yml@v2.0.0
        with:
          artifact_path: ${{ env.artifact_path }}/maven
          version: ${{ github.ref_name }}

      - name: Verify SLSA Provenance for Maven
        run: |
          curl -Lo slsa-verifier https://github.com/slsa-framework/slsa-verifier/releases/latest/download/slsa-verifier-linux-amd64
          chmod +x slsa-verifier
          ./slsa-verifier verify-artifact \
            --provenance ${{ env.artifact_path }}/maven/target/*.slsa.json \
            --source github.com/${{ github.repository }} \
            --builder-id https://github.com/slsa-framework/slsa-github-generator \
            ${{ env.artifact_path }}/maven/target/*.jar > maven_verification_output.txt 2>&1
          echo "<html><body><h2>Maven SLSA Verification Report</h2><pre>" > maven_verification_report.html
          cat maven_verification_output.txt >> maven_verification_report.html
          echo "</pre></body></html>" >> maven_verification_re
